### ISSUE TITLE
Erasure-coding library research

### ISSUE THREAD

**Issue by asmie** [eigerco/strawberry#3]
There is a need to research library for erasure encoding.

Something similar to the Rust one:
https://github.com/paritytech/erasure-coding/blob/main/src/subshard.rs

Ensure the library is aligned with GP Appendix H.

Test vectors from Gavin:
https://gist.github.com/gavofyork/4cde92327cd91eff3e2ab91d316cb83a

Test vectors in the official repo (PRed):
https://github.com/w3f/jamtestvectors/pull/4

**Comment by greywolve** [comment]
After more research I think we should wrap and use [this lib](https://github.com/AndersTrier/reed-solomon-simd) via FFI. Other reed solomon GF16 libraries seem to require the shard size to be a multiple of 64 bytes, this one doesn't.
